language: node_js

sudo: false

cache: yarn

node_js:
  - '6'

install:
  - yarn install --pure-lockfile

script:
  - yarn build
  - yarn test
  - yarn lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
